### ISSUE TITLE
[RequiredPlugin(unnamed)] Plugin not found: "BeamAdapter"

### ISSUE THREAD

**Issue by JYMiracle305** [lkarstensen/stEVE_training#1]
I am using sofa 23.06, but this error is reported. Is there something missing in my configuration, or is there a problem with the interface of this version?
![image](https://github.com/user-attachments/assets/24df1a6c-213f-41a0-8e34-15d0a543db4f)

**Comment by lkarstensen** [comment]
Hi Ji,

Sorry for the late reply. It seems you have the base version of SOFA and the BeamAdapter Plugin (the core mechanics for simulating guide wires and catheters) is missing. Did you use a pre compiled version from Sofa or did you compile it yourself?

Best Regards,
Lennart

**Comment by JYMiracle305** [comment]
Lennart，
Thanks for your reply. Your method works. I have pulled the repo of BeamAdapter into Sofa manually. After recompiling Sofa, the whole project is been built successfully. Thanks

**Comment by lkarstensen** [comment]
Good to hear. Let me know if you have any other problems. I want to implement compatibility to newer SOFA versions and include an option for an auto-install soon. If there’s anything else not working would be best to do it in one go.
